version: '1'
services:

  server:
    build: .
    ports:
      - "80:7001"
    networks:
      - ethereal-network

  redis:
    image: redis
    ports:
     - "6379"
    networks:
      - ethereal-network

networks:
  ethereal-network:
    driver: bridge